actions/setup-dotnet

lib/installer.js
src/installer.ts

Add DOTNET_ROOT

---

.github/workflows/workflow.yml
externals/install-dotnet.ps1
externals/install-dotnet.sh

Updating the install scripts to the latest versions from https://dot.net/v1/dotnet-install.sh and https://dot.net/v1/dotnet-install.psq to fix the failing tests
[Example Failing Test on master](https://github.com/actions/setup-dotnet/commit/d9c317d9d5f7adf485b8378b3a493539653b4cf5/checks?check_suite_id=260175787)

Update external install scripts

---

lib/installer.js
src/installer.ts

Dotnet deprecated the current endpoint we're using and is planning on removing it next week. This updates to the new endpoint.
Fixes #24

Update from obsolete endpoint

---

.github/csc.json

1. Adding `fromPath` parameter. Fixes #17 
1. Expand regex to capture code analysis errors/warnings
1. Fixing line identification

Fixing dotnet compiler Problem Matcher

---

README.md

Given the LTS release of .NET Core it's good practice that any samples using the SDK should use the supported versions.  2.2 is no longer a supported version in a month or so and the latest SDK should be used in examples.  Minor change, but important for copy/paste folks.

Updating readme snippets to show latest SDK

---

.github/workflows/workflow.yml
externals/get-os-distro.sh

With the changes for releases-index, the os mac could no longer be found. This change switches to using osx as the os name which is used in the new json.
Example uses osx-x64, but does not use mac in the version description: https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.1/releases.json

Set osx as the os name

---

lib/setup-dotnet.js
src/setup-dotnet.ts

Move back to deploying from master. There are no changes in releases/v1 that needed to be moved back to master.

Remove warning from master branch

---

README.md

Fixes: #91, #10, #22 
These do not change any dotnet defaults, but adds documentation to make defaults and uses clear to users.

Include useful environment variables in the README

---

.github/workflows/workflow.yml
__tests__/authutil.test.ts
__tests__/verify-dotnet.ps1
__tests__/verify-dotnet.sh
dist/index.js
src/authutil.ts

Honor specified nuget file location

---

README.md

Changed link pointing to github docs.
There seems to be a redirect implemented on the docs page, so the current link still works - for now 😉
The page anchor helps find the info more quickly though.

Update link to pre-installed runner Software

---

README.md

.NET Core 2.2 and 3.0 are no longer supported and should not be in the examples.
All versions were changed to pull in the latest revision as people might copy this without
checking all accepted version formats and getting the latest revision is good security practice.

Remove unsupported versions of .NET from README

---

dist/index.js
src/authutil.ts

The task finds Nuget config file with name `nuget.config` in root directory by default. Added a possibility to use various formats for file name: `NuGet.config`, `NuGet.Config` without specifying `config-file` input explicitly.
#181 

Support various nuget.config name formats

---

dist/index.js
src/setup-dotnet.ts

Parsing of the global.json fail if its saved with BOM
https://github.com/actions/setup-dotnet/issues/185

Add workaround to fix BOM-related error  during parsing global.json

---

.github/workflows/release-new-action-version.yml

Currently, releasing new versions of the `setup-dotnet` action is the manual and unreliable process. In scope of this PR we added a workflow file in order to automate creating/updating a major version tag when a new `setup-dotnet` version is released. We use the [actions/publish-action](https://github.com/actions/publish-action) action for this purpose. 
**Details:**
We added:
- the `workflow_dispatch` event to manually trigger a workflow run;
- the `release` webhook event to automatically trigger workflow run when a new action version is released;
- the `releaseNewActionVersion` environment with protection rules to require a manual approval.
Reverting changes is almost the same process as updating major version tag. In case of any issues related to the updated tag, we …

Automate releasing new versions of the setup-dotnet action

---

__tests__/clear-toolcache.ps1

Clear toolcache step takes  more than ~9 minutes for Windows. To save time we should use move instead of remove operation.

Move toolcache folder

---

README.md

dotnet env variables documentation has moved to a new page.
Old: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#environment-variables
New: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables

Update link to dotnet environment variables docs

---

dist/index.js
src/installer.ts

Implements a warning when users try to install an EOL version of .NET.
Closes #180

Warn users when installing EOL .NET versions

---

dist/index.js
src/setup-dotnet.ts

I have workflows which install both a fixed version of the SDK and a secondary SDK, for testing purposes, specified by a matrix entry. Sometimes, the fixed version and the matrix version are the same. In those cases, I don't want to try and install the same SDK twice. This PR solves this by ignoring duplicate versions in the action.
None.

avoid installing the same version multiple times

---

.github/workflows/check-dist.yml
.github/workflows/licensed.yml
.github/workflows/test-dotnet.yml
.github/workflows/workflow.yml
README.md
docs/contributors.md
externals/install-dotnet.sh
package.json

- Updating documentation to the action version `v2`
- Bump to action/checkout@v3
- Bump to action/setup-node@v3
- Update installer scripts

Update docs to v2

---

.github/workflows/workflow.yml
README.md
action.yml
dist/index.js
src/setup-dotnet.ts

Our workflow involves doing a checkout to the subdirectory of the workspace. This results in a similar situation to that described in #253, where the global.json is not present in the root of the workspace.
This PR proposes solving this with a `global-json-file` input, similar to [`node-version-file` from actions/setup-node](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file).
* Unlike `node-version-file`, `global-json-file` can be used alongside `dotnet-version` since multiple versions are already allowed.
* If `global-json-file` is specified, it is an error for it not to exist.
* As before, if `global-json-file` is not specified `./global.json` is still searched, but only if `dotnet-version` was not, and the debug message of _No …

add global-json-file input

---

package-lock.json

Dependabot cannot update vulnerable package `minimist` automatically:
https://github.com/actions/setup-dotnet/security/dependabot
Updated manually.

Update vulnerable packages

---

__tests__/setup-dotnet.test.ts
action.yml
dist/index.js
src/setup-dotnet.ts

`getBooleanInput()` function was added since @actions/core@1.3.0 (actions/toolkit#725).
This PR uses it to reduce code path.
:warning:This change is **BREAKING CHANGE** if `include-prerelease` set invalid value.
```yaml
- uses: actions/setup-dotnet@v1
with:
dotnet-version: '6.0.x'
include-prerelease: 'foo' # Resolved 'false' before, but throws error now
```
None.

Use `core.getBooleanInput()` to resolve `include-prerelease` option

---

docs/adrs/v3-setup-dotnet.md

This PR outlines the basic proposals for the v3 version of `setup-dotnet`.
Internal issue: https://github.com/actions/virtual-environments-internal/issues/1807
https://github.com/actions/setup-dotnet/pull/171#discussion_r627211129:
We have a bunch of .NET Core versions pre-installed on images. And the problem is that action works very inconsistent on different platforms.
- Ubuntu:
Pre-installed location (where .NET is pre-installed): “/usr/share/dotnet”
Action installs to: “/home/runner/.dotnet”
- Windows:
Pre-installed location: “C:\Program Files\dotnet”
Action installs to “C:\Users\runneradmin\AppData\Local\Microsoft\dotnet”
- MacOS:
Pre-installed location: “/Users/runner/.dotnet”
Action installs to “/Users/runner/.dotnet”
How it works currently on macOS
Pre-installed location and …

V3 setup-dotnet ADR

---

dist/index.js
externals/install-dotnet.sh
src/installer.ts

This PR fixes an issue where older versions of powershell (powershell versus pwsh (powershell core) is used on windows. Due to that, the `install-dotnet` script fails to detect it is on a windows arm device, and installs the x64 version of dotnet. 
So now we try to use powershell core if it exists, then fallback to powershell. This should not impact linux/mac os in any way.

Add support for Windows-arm

---

README.md
dist/index.js
package-lock.json
package.json
src/installer.ts
src/utils.ts

In scope of this PR the `DOTNET_INSTALL_DIR` environment variable was enabled to add the ability to change the installation directory for .NET SDK. The `DOTNET_INSTALL_DIR` can be helpful when access to the default installation directory, for instance, on self-hosted runners, is denied. Also, the `DOTNET_INSTALL_DIR` environment variable was documented.
[Issue](https://github.com/actions/setup-dotnet/issues/327)

Enable ability to change .NET SDK installation directory by `DOTNET_INSTALL_DIR` environment variable

---

.licenses/npm/@actions/core.dep.yml
dist/index.js
package-lock.json
package.json

This updates @actions/core to use the [file version](https://github.com/actions/toolkit/pull/1178) of `save-state` and
`set-output` workflow commands.

Update @actions/core to 1.10.0

---

.github/workflows/basic-validation.yml
.github/workflows/check-dist.yml
.github/workflows/codeql-analysis.yml
.github/workflows/e2e-tests.yml
.github/workflows/licensed.yml
.github/workflows/release-new-action-version.yml
.github/workflows/workflow.yml
__tests__/verify-no-unstaged-changes.sh
package.json

In the scope of this PR we update workflows in the repo to use reusable-workflows from the [repo](https://github.com/actions/reusable-workflows).
[#4595](https://github.com/actions/runner-images-internal/issues/4595)

Update action to use reusable workflows

---

dist/index.js
src/installer.ts

During the installation of .NET using the setup-dotnet action some errors may be thrown. Usually, an error message should contain a comprehensive reason for the error, but in the setup-dotnet, there is a case where it's not like that. [These](https://github.com/actions/setup-dotnet/blob/main/src/installer.ts#L239-L246) lines of code contain a small bug that should be fixed.
[Link](https://github.com/actions/runner-images-internal/issues/4785)

Make throwing errors in setup-dotnet more informative

---

__tests__/installation-scripts.test.ts

Increased amount of retries for tests that require fetching dotnet-install scripts as they tend to fail from time to time. 
—

Increase amount of retries for Dotnet installation scripts tests

---

.github/workflows/e2e-tests.yml
__tests__/installer.test.ts
dist/setup/index.js
src/installer.ts

**Description**
- Added LTS runtime installation before requested dotnet installation:
When dotnet is installed after usage of some other version, [install script fails to override dotnet.exe](https://github.com/nikolai-laevskii/setup-dotnet/actions/runs/4961107288/jobs/8877470722) as it appears to be used by a process. Workaround is to pass `--skip-unversioned-files` flag to the install script and avoid overriding this file altogether. However, to ensure better compatibility and to avoid vulnerability issues, LTS runtime is now installed first, providing up-to-date unversioned files (such as CLI) for further usage.
- Added E2E tests that check for the problem described in the issue
- Additional E2E tests were added to address this issue in the future.
- The new E2E test failing on the …

Sequential version install fix

---

README.md

update README with latest version
I wasn't immediately aware that v4 was the current version.
It's in releases but I think the README should reflect the latest version particularly since v3 gives depreciation warnings

Update README.md to use latest action version

---

dist/cache-save/index.js
dist/setup/index.js
externals/install-dotnet.sh
src/cache-utils.ts

I'm fixing the logic within helper method `isGhes` to ensure that it doesn't misrecognize GitHub Enterprise Cloud instances as GHES instances.
https://github.com/newsroom/press-releases/data-residency-in-the-eu

Revise `isGhes` logic

---

README.md

Add new Recommended permissions section to the README file.

README update - add permissions section

---

.github/workflows/publish-immutable-actions.yml

This workflow file publishes new action releases to the immutable action package of the same name as this repo.
This is part of the Immutable Actions project which is not yet fully released to the public. First party actions like this one are part of our initial testing of this feature.

V3 - Add workflow file for publishing releases to immutable action package

---

.github/workflows/e2e-tests.yml
.github/workflows/test-dotnet.yml
README.md
__tests__/verify-dotnet.ps1
externals/install-dotnet.ps1
externals/install-dotnet.sh

- This pull request eliminates references to older .NET versions from the repository. It also updates the README to accurately reflect the currently available versions and revises the end-to-end (E2E) tests to align with these changes.
- Pull the latest version of installer scripts via `npm run update-installers`.
https://github.com/actions/setup-dotnet/issues/645

Remove Support for older .NET Versions and Update installers scripts

---

.github/workflows/basic-validation.yml
.github/workflows/check-dist.yml
.licenses/npm/@types/node.dep.yml
.licenses/npm/undici-types.dep.yml
README.md
action.yml
dist/cache-save/index.js
dist/setup/index.js
package-lock.json
package.json
tsconfig.json

Bump Node.js version to 24 in workflows, action metadata, and engines. Update TypeScript target to ES2022 and use native async/await instead of __awaiter in compiled JS. Upgrade @types/node to 24.1.0 and update undici-types. Remove legacy async helpers and refactor code for improved readability and compatibility with modern Node.js.
Describe your changes.

Update to Node.js 24 and modernize async usage
