actions/setup-dotnet

lib/installer.js
src/installer.ts

Fixes #29
Check the issue for reasoning. The listed [workaround](https://github.com/rmunn/Testing/commit/fc604507611c57d998bd02e22ddad4001edb40d3#diff-be4b0426c0051d8af0d3a68817855541R20-R22) worked for me in my [reproduction repo](https://github.com/rojepp/dotnetsay).
I also tested this PR against the same repo https://github.com/rojepp/dotnetsay/blob/master/.github/workflows/test.yml#L13

Include version/architecture in DOTNET_ROOT

---

README.md

Makes the README more clear about environment being set-up and gives valid examples of versions that can be installed.
Fixes #43

Update README to show real matrix examples

---

lib/installer.js
lib/setup-dotnet.js
src/setup-dotnet.ts

Completes step 2 in #20. This change should not go to the releases branch.

Warn on master

---

externals/install-dotnet.ps1
externals/install-dotnet.sh
package-lock.json
package.json

- Updated installer scripts
- Added an npm script to aid in updating installer scripts

Updating installer scripts

---

README.md
__tests__/installer.test.ts
action.yml
externals/install-dotnet.sh
src/installer.ts

Added support for latest patch, e.g. 3.1.x

---

README.md

YAML Format of the code at 'Example usage' with Environment Variables

YAML Formatting at a example workflow

---

.github/workflows/workflow.yml
.licenses/npm/@actions/core.dep.yml
dist/index.js
package-lock.json
package.json

The newest toolkit version uses [Environment files](https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files) to communicate with the Runner. This pr moves towards the new way of communicating with the runner and updates the appropriate toolkit version

Update `@actions/core` Version and move towards uses environment files to talk to runner

---

externals/install-dotnet.ps1
externals/install-dotnet.sh

Installer scripts (`install-dotnet.ps1` and `install-dotnet.sh`) were updated to the latest version via `npm update-installers` command.
Issue #162

Update installer scripts

---

action.yml

Fixes #84
Help to clarify scenario where no dotnet version is given

Action input text update for version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

In scope of this pull request we add such logic as
- disable creating blank issue
- add needs triage label in the first time issue is created
**Related issue:** https://github.com/actions/virtual-environments-internal/issues/1700

Restrict blank issues

---

.github/CODEOWNERS

Add @actions/virtual-environments-owners to CODEOWNERS file

Add @actions/virtual-environments-owners to CODEOWNERS file

---

README.md

Add preview example to README

---

externals/install-dotnet.ps1
externals/install-dotnet.sh

Pull the latest installers scripts via `npm run update-installers`

Update installers scripts

---

action.yml

Fixes #209 by adding a few more terms for search discoverability
#209 
No documentation or test changes needed...product description change only.

Update description for action

---

action.yml

Action description must be less than 125 characters.

Rework action description

---

README.md

Notice the rogue space in the sample yml?
This is intended to fix dat.

🖊 Fix space-o that would break yml

---

.github/workflows/licensed.yml

Fix the Licensed workflow

---

README.md

To align the second code sample with the other samples, I have moved the checkout step above the install step.

Moved checkout above setup step to align with the other samples

---

externals/install-dotnet.ps1
externals/install-dotnet.sh

Updated the dotnet-install PowerShell and bash scripts to the latest version. The current scripts are unable to install .NET 7 Preview 1 SDK on self-hosted runners due to the lack of the dotnetbuilds.azureedge.net Azure Feed.
https://github.com/dotnet/core/issues/7213

Updated dotnet-install scripts to latest version

---

README.md

Since multiple versions were introduced, there's no need to run two setup steps anymore.
https://github.com/actions/setup-dotnet/issues/146

switch side by side testing example to single setup step

---

externals/install-dotnet.sh
package-lock.json

Following package.json update, we need to update package-lock.json as well running `npm version x.y.z`

Update package lock version

---

README.md

In the scope of this PR, the README.md file was updated to clarify current .NET installation process.
[#351](https://github.com/actions/setup-dotnet/issues/351)

Update README.md to clarify installation process

---

.licenses/npm/fast-xml-parser.dep.yml
dist/setup/index.js
externals/install-dotnet.sh
package-lock.json
package.json

In the scope of this PR the fast-xml-parser was update to the `v4.2.4` as suggested https://github.com/actions/setup-dotnet/pull/434. Solution was rebuilt and dotnet installers scripts were updated as well.
[Dependabot's PR](https://github.com/actions/setup-dotnet/pull/434)

Update fast-xml-parser and dotnet installer scripts

---

README.md

Updated links to the runner software.

Update links to runner software

---

externals/install-dotnet.sh

To fix Basic Validation failure checks.

Fix failure checks on Basic Validation
